/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Timestamp = IDL.Int;
export const BlogPost = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'published' : IDL.Bool,
  'createdAt' : Timestamp,
  'author' : IDL.Text,
});
export const VisitorQuery = IDL.Record({
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : Timestamp,
  'message' : IDL.Text,
});
export const Notice = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'active' : IDL.Bool,
  'createdAt' : Timestamp,
  'message' : IDL.Text,
});
export const VisitorID = IDL.Record({
  'service' : IDL.Text,
  'expiresAt' : Timestamp,
  'username' : IDL.Text,
  'password' : IDL.Text,
  'createdAt' : Timestamp,
  'visitorName' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const NadiPlanetInfo = IDL.Record({
  'subLord' : IDL.Text,
  'isRetrograde' : IDL.Bool,
  'name' : IDL.Text,
  'pada' : IDL.Nat,
  'sign' : IDL.Text,
  'degree' : IDL.Float64,
  'nakLord' : IDL.Text,
  'houseNum' : IDL.Nat,
  'degreeStr' : IDL.Text,
  'nakshatra' : IDL.Text,
});
export const NadiChartResult = IDL.Record({
  'dashaBalance' : IDL.Text,
  'planets' : IDL.Vec(NadiPlanetInfo),
  'ascendant' : NadiPlanetInfo,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Person = IDL.Record({
  'dob' : IDL.Opt(IDL.Text),
  'tob' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Text,
  'dob' : IDL.Opt(IDL.Text),
  'tob' : IDL.Opt(IDL.Text),
  'palmPhotos' : IDL.Vec(IDL.Opt(ExternalBlob)),
  'question' : IDL.Text,
  'authorId' : IDL.Opt(IDL.Principal),
  'seedNumber' : IDL.Opt(IDL.Nat),
  'city' : IDL.Opt(IDL.Text),
  'submittedAt' : Timestamp,
  'birthCountry' : IDL.Opt(IDL.Text),
  'handPicture' : IDL.Opt(ExternalBlob),
  'state' : IDL.Opt(IDL.Text),
  'visitorName' : IDL.Text,
  'pastLifeNotes' : IDL.Text,
  'serviceId' : IDL.Nat,
  'relationshipPerson2' : IDL.Opt(Person),
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'email' : IDL.Text,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'price' : IDL.Nat,
});
export const NumerologyUser = IDL.Record({
  'username' : IDL.Text,
  'passwordHash' : IDL.Text,
  'sectionLevel' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'adminCreateNotice' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'adminCreatePost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'adminCreateVisitorId' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'adminDeleteNotice' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'adminDeletePost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'adminDeleteVisitorId' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'adminGetAllPosts' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(BlogPost)],
      ['query'],
    ),
  'adminGetVisitorQueries' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(VisitorQuery)],
      ['query'],
    ),
  'adminListNotices' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Notice)],
      ['query'],
    ),
  'adminListVisitorIds' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(VisitorID)],
      ['query'],
    ),
  'adminPublishPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'adminToggleNotice' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'adminUpdatePost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculateNadiPlanets' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
      [IDL.Variant({ 'ok' : NadiChartResult, 'err' : IDL.Text })],
      [],
    ),
  'createPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
  'deleteInquiry' : IDL.Func([IDL.Text], [], []),
  'deletePost' : IDL.Func([IDL.Text], [], []),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getAllPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllPostsAdmin' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVisitorQueries' : IDL.Func([], [IDL.Vec(VisitorQuery)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'noticeCreate' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'noticeDelete' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'noticeList' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
  'noticeListAll' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Notice)],
      ['query'],
    ),
  'noticeToggleActive' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'numerologyCreateUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'numerologyDeleteUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'numerologyListUsers' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(NumerologyUser)],
      ['query'],
    ),
  'numerologyLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'openCreateVisitorId' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'openDeleteVisitorId' : IDL.Func([IDL.Text], [], []),
  'openListVisitorIds' : IDL.Func([], [IDL.Vec(VisitorID)], ['query']),
  'publishPost' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'serviceGetAllAccess' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
      ['query'],
    ),
  'serviceIsPublic' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'serviceSetPublic' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'submitInquiry' : IDL.Func([Inquiry], [IDL.Text], []),
  'submitVisitorQuery' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updatePost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
  'visitorCreateId' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [],
      [],
    ),
  'visitorDeleteId' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'visitorListIds' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(VisitorID)],
      ['query'],
    ),
  'visitorLoginByEmail' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(IDL.Record({ 'service' : IDL.Text, 'visitorName' : IDL.Text }))],
      ['query'],
    ),
  'visitorValidateId' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Timestamp = IDL.Int;
  const BlogPost = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'published' : IDL.Bool,
    'createdAt' : Timestamp,
    'author' : IDL.Text,
  });
  const VisitorQuery = IDL.Record({
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : Timestamp,
    'message' : IDL.Text,
  });
  const Notice = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'active' : IDL.Bool,
    'createdAt' : Timestamp,
    'message' : IDL.Text,
  });
  const VisitorID = IDL.Record({
    'service' : IDL.Text,
    'expiresAt' : Timestamp,
    'username' : IDL.Text,
    'password' : IDL.Text,
    'createdAt' : Timestamp,
    'visitorName' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const NadiPlanetInfo = IDL.Record({
    'subLord' : IDL.Text,
    'isRetrograde' : IDL.Bool,
    'name' : IDL.Text,
    'pada' : IDL.Nat,
    'sign' : IDL.Text,
    'degree' : IDL.Float64,
    'nakLord' : IDL.Text,
    'houseNum' : IDL.Nat,
    'degreeStr' : IDL.Text,
    'nakshatra' : IDL.Text,
  });
  const NadiChartResult = IDL.Record({
    'dashaBalance' : IDL.Text,
    'planets' : IDL.Vec(NadiPlanetInfo),
    'ascendant' : NadiPlanetInfo,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Person = IDL.Record({
    'dob' : IDL.Opt(IDL.Text),
    'tob' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Text,
    'dob' : IDL.Opt(IDL.Text),
    'tob' : IDL.Opt(IDL.Text),
    'palmPhotos' : IDL.Vec(IDL.Opt(ExternalBlob)),
    'question' : IDL.Text,
    'authorId' : IDL.Opt(IDL.Principal),
    'seedNumber' : IDL.Opt(IDL.Nat),
    'city' : IDL.Opt(IDL.Text),
    'submittedAt' : Timestamp,
    'birthCountry' : IDL.Opt(IDL.Text),
    'handPicture' : IDL.Opt(ExternalBlob),
    'state' : IDL.Opt(IDL.Text),
    'visitorName' : IDL.Text,
    'pastLifeNotes' : IDL.Text,
    'serviceId' : IDL.Nat,
    'relationshipPerson2' : IDL.Opt(Person),
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'email' : IDL.Text,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'price' : IDL.Nat,
  });
  const NumerologyUser = IDL.Record({
    'username' : IDL.Text,
    'passwordHash' : IDL.Text,
    'sectionLevel' : IDL.Nat,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'adminCreateNotice' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'adminCreatePost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'adminCreateVisitorId' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'adminDeleteNotice' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'adminDeletePost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'adminDeleteVisitorId' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'adminGetAllPosts' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(BlogPost)],
        ['query'],
      ),
    'adminGetVisitorQueries' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(VisitorQuery)],
        ['query'],
      ),
    'adminListNotices' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Notice)],
        ['query'],
      ),
    'adminListVisitorIds' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(VisitorID)],
        ['query'],
      ),
    'adminPublishPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'adminToggleNotice' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'adminUpdatePost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculateNadiPlanets' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [IDL.Variant({ 'ok' : NadiChartResult, 'err' : IDL.Text })],
        [],
      ),
    'createPost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Text], []),
    'deleteInquiry' : IDL.Func([IDL.Text], [], []),
    'deletePost' : IDL.Func([IDL.Text], [], []),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getAllPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllPostsAdmin' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVisitorQueries' : IDL.Func([], [IDL.Vec(VisitorQuery)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'noticeCreate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'noticeDelete' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'noticeList' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
    'noticeListAll' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Notice)],
        ['query'],
      ),
    'noticeToggleActive' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'numerologyCreateUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'numerologyDeleteUser' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'numerologyListUsers' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(NumerologyUser)],
        ['query'],
      ),
    'numerologyLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'openCreateVisitorId' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'openDeleteVisitorId' : IDL.Func([IDL.Text], [], []),
    'openListVisitorIds' : IDL.Func([], [IDL.Vec(VisitorID)], ['query']),
    'publishPost' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'serviceGetAllAccess' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool))],
        ['query'],
      ),
    'serviceIsPublic' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'serviceSetPublic' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'submitInquiry' : IDL.Func([Inquiry], [IDL.Text], []),
    'submitVisitorQuery' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updatePost' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [], []),
    'visitorCreateId' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [],
        [],
      ),
    'visitorDeleteId' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'visitorListIds' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(VisitorID)],
        ['query'],
      ),
    'visitorLoginByEmail' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Opt(
            IDL.Record({ 'service' : IDL.Text, 'visitorName' : IDL.Text })
          ),
        ],
        ['query'],
      ),
    'visitorValidateId' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };